baseURL = "https://blog.wenjy.top"
languageCode = "zh-CN"
title = "Wenjy's Blog"
theme = "maupassant"

[author]
  name = "江湖义气"

[params]
  author = "江湖义气"
  subtitle = "回首往事，不会因为虚度年华而悔恨，也不会因为碌碌无为而感到羞愧。"
  keywords = "PHP,Swoole,Web开发"
  description = "记录工作、学习中遇到的问题和解决方法..."
  busuanzi = true

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about"
    weight = 3

[[params.links]]
  title = "MIKELIN | 关注科技，弘扬互联网精神！"
  name = "MIKELIN"
  url = "https://mikelin.cn"

[[params.links]]
  title = "江湖义气的网络日志"
  name = "江湖义气的网络日志"
  url = "https://blog.wenjy.top"

[params.utteranc]
    enable = true
    repo = "wenjy/blog"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
