name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    # runs-on: macOS-10.14
    # runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hexo
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Build
        env:
          GH_ACTION_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'wenjy'
          git config --global user.email 'wenjy1314@gmail.com'
          yarn global remove hexo-cli
          yarn global add hexo-cli --prefix /usr/local
          yarn info hexo-cli
          echo $PATH
          yarn install

      - name: Deploy Hexo
        env:
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          hexo clean clean && hexo generate && hexo deploy

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
