name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    # runs-on: macOS-10.14
    # runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup Hexo
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.x'

      - name: Build
        env:
          GH_ACTION_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          NEXT_VERSION: v1.3.2
        run: |
          mkdir -p ~/.ssh/
          echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'wenjy'
          git config --global user.email 'wenjy1314@gmail.com'
          npm i -g hexo-cli
          npm i
          npm i -S hexo-prism-plugin
          npm install hexo-generator-search --save
          npm i hexo-permalink-pinyin --save
          npm i --save hexo-wordcount
          npm install hexo-generator-feed --save
          git clone --branch ${NEXT_VERSION} --depth=10  git@github.com:wenjy/hexo-theme-matery.git themes/hexo-theme-matery
          git checkout -b ${NEXT_VERSION}

      - name: Deploy
        env:
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          hexo generate && hexo algolia && hexo deploy
